import Head from 'next/head';
import Link from 'next/link';

import { HouseItem } from '../components/HouseItem';
import { API_URL } from '../config';

export default function Home({ houses }) {
  console.log(houses);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello World</h1>
      {houses.length > 0 &&
        houses.map(house => <HouseItem house={house} key={house.id} />)}

      {houses.length > 0 && (
        <Link href='/houses'>
          <a>see all houses</a>
        </Link>
      )}
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`${API_URL}/houses?featured=true`);
  const houses = await res.json();

  return {
    props: {
      houses,
      revalidate: 1,
    },
  };
};
